---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    selector: 
      matchLabels: 
        app: "order"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "order"
      spec: 
        containers: 
          - 
            name: "order"
            image: "order"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "order"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    selector: 
      matchLabels: 
        app: "delivery"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "delivery"
      spec: 
        containers: 
          - 
            name: "delivery"
            image: "delivery"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "delivery"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "inventory"
    labels: 
      app: "inventory"
  spec: 
    selector: 
      matchLabels: 
        app: "inventory"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "inventory"
      spec: 
        containers: 
          - 
            name: "inventory"
            image: "inventory"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "inventory"
    labels: 
      app: "inventory"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "inventory"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "dashboard"
    labels: 
      app: "dashboard"
  spec: 
    selector: 
      matchLabels: 
        app: "dashboard"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "dashboard"
      spec: 
        containers: 
          - 
            name: "dashboard"
            image: "dashboard"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "dashboard"
    labels: 
      app: "dashboard"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "dashboard"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "notifcation"
    labels: 
      app: "notifcation"
  spec: 
    selector: 
      matchLabels: 
        app: "notifcation"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "notifcation"
      spec: 
        containers: 
          - 
            name: "notifcation"
            image: "notifcation"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "notifcation"
    labels: 
      app: "notifcation"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "notifcation"
